services:
  frontend:
    container_name: toogoodtogo
    build: .
    image: toogoodtogo:latest
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=toogoodtogo.settings.production
      - DATABASE_URL=postgres://postgres:password@db:5432/too_good_to_go
      - ALLOWED_HOSTS=localhost
      - SECRET_KEY='a not so secret key'
    command: gunicorn toogoodtogo.wsgi:application --bind 0.0.0.0:8000

  db:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=too_good_to_go
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -t 1"]
      interval: 1s
      timeout: 1s
      retries: 5

  django-migrate:
    image: toogoodtogo:latest
    command: python manage.py migrate
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/too_good_to_go
      - DJANGO_SETTINGS_MODULE=toogoodtogo.settings.production
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
