# Generated by Django 4.1.7 on 2023-02-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_keeping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreading',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock_keeping.shop'),
            preserve_default=False,
        ),
    ]
