# Generated by Django 4.1.7 on 2023-03-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_keeping', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockreading',
            old_name='expiry',
            new_name='expires_at',
        ),
        migrations.RenameField(
            model_name='stockreading',
            old_name='occurrence',
            new_name='scanned_at',
        ),
    ]
