# Generated by Django 4.1.7 on 2023-03-01 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_keeping', '0004_rename_expiry_stockreading_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_keeping.shop'),
        ),
    ]
