name: Run tests

on : [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: toogoodtogo.settings.development
    services:
      postgres:
        image: postgres:15.2-alpine
        env:
          POSTGRES_PASSWORD: password
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install -r requirements.txt
      # wait for Postgres to be ready
      - run: pg_isready --host localhost --timeout 5
      - run: pytest -v
